Repository neulsom-EZY/EZY-server, pull requests merged in 2021-11, with the labels that each got.

#281 심부름 실패
  src/main/java/com/server/EZY/model/plan/errand/controller/ErrandStatusCycleController.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandService.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/main/java/com/server/EZY/notification/enum_type/FcmActionSelector.java
  src/main/java/com/server/EZY/notification/service/feature/FcmActiveSender.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandStatusCycleTest.java
Labels: code-review, Build-success

#282 회원가입 테스트 보완
  src/test/java/com/server/EZY/model/member/service/MemberServiceTest.java
Labels: Build-success

#283 Fail To Send Message Exception
  src/main/java/com/server/EZY/exception/authentication_number/AuthenticationNumberExceptionHandler.java
  src/main/java/com/server/EZY/exception/authentication_number/AuthenticationNumberExceptionHandlerImpl.java
  src/main/java/com/server/EZY/exception/authentication_number/controller/AuthenticationNumberExceptionController.java
  src/main/java/com/server/EZY/exception/authentication_number/exception/AuthenticationNumberTransferFailedException.java
  src/main/java/com/server/EZY/exception/authentication_number/exception/FailedToSendMessageException.java
  src/main/java/com/server/EZY/model/member/service/message/MessageServiceImpl.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
  src/test/java/com/server/EZY/exception/AuthenticationNumberExceptionHandlerTest.java
Labels: Build-success

#285 member controller test
  src/test/java/com/server/EZY/model/member/controller/MemberControllerTest.java
Labels: code-review, Build-success

#284 심부름 실패 기능 추가
  src/main/java/com/server/EZY/model/plan/errand/controller/ErrandStatusCycleController.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandService.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/main/java/com/server/EZY/notification/enum_type/FcmActionSelector.java
  src/main/java/com/server/EZY/notification/service/feature/FcmActiveSender.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandStatusCycleTest.java
Labels: code-review, Build-success

#286 Feature/fcm test mode
  src/main/java/com/server/EZY/config/message/MessageConfiguration.java
  src/main/java/com/server/EZY/notification/config/FirebaseMessagingConfig.java
  src/main/java/com/server/EZY/notification/service/FirebaseMessagingService.java
  src/test/resources/application.yml
Labels: code-review, Build-success

#288 FCM push알람 비동기 처리 + 서버 시작시 Member더미 데이터 생성
  src/main/java/com/server/EZY/dummy_for_dev/GenerateMemberAccount.java
  src/main/java/com/server/EZY/exception/fcm_push/FcmPushFailException.java
  src/main/java/com/server/EZY/notification/service/FirebaseMessagingService.java
  src/main/java/com/server/EZY/notification/service/feature/FcmActiveSender.java
Labels: code-review, Build-success

#289 ErrandEntity ERD에 없는 필드 제거
  src/main/java/com/server/EZY/model/plan/errand/ErrandEntity.java
  src/test/java/com/server/EZY/model/plan/errand/ErrandTest.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandStatusCycleTest.java
Labels: hotfix, Urgent, Build-success

#287 심부름 리펙터링
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/main/java/com/server/EZY/notification/dto/FcmSourceDto.java
  src/main/java/com/server/EZY/notification/enum_type/FcmRole.java
Labels: code-review, Build-success

#291 Hotfix
  src/main/java/com/server/EZY/model/plan/tag/dto/TagSetDto.java
  src/test/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImplTest.java
Labels: bug, hotfix

#292 Hotfix
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandServiceImplTest.java
  src/test/java/com/server/EZY/model/plan/tag/controller/TagControllerTest.java
  src/test/java/com/server/EZY/model/plan/tag/service/TagServiceImplTest.java
  src/test/java/com/server/EZY/notification/service/FirebaseMessagingServiceTest.java
Labels: bug, hotfix

#294 Feature/personalplan query
  src/main/java/com/server/EZY/model/plan/personal/controller/PersonalPlanController.java
  src/main/java/com/server/EZY/model/plan/personal/dto/PersonalPlanDto.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanCustomRepository.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanCustomRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImpl.java
  src/main/java/com/server/EZY/model/plan/personal/service/strategy/PersonalPlanStrategyImpl.java
  src/test/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImplTest.java
Labels: bug, hotfix, Build-success, Fix-todo

#295 Hotfix
  src/main/java/com/server/EZY/model/plan/errand/ErrandEntity.java
  src/main/java/com/server/EZY/model/plan/errand/dto/ErrandSetDto.java
  src/main/java/com/server/EZY/model/plan/errand/repository/errand_detail/ErrandDetailRepository.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/test/java/com/server/EZY/model/plan/errand/ErrandTest.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandServiceImplTest.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandStatusCycleTest.java
Labels: code-review, hotfix, Urgent, Build-success

#296 Feature/get errand info
  src/main/java/com/server/EZY/model/plan/errand/controller/ErrandController.java
  src/main/java/com/server/EZY/model/plan/errand/dto/ErrandResponseDto.java
  src/main/java/com/server/EZY/model/plan/errand/dto/ErrandSetDto.java
  src/main/java/com/server/EZY/model/plan/errand/repository/errand/ErrandCustomRepository.java
  src/main/java/com/server/EZY/model/plan/errand/repository/errand/ErrandCustomRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandService.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandServiceImplTest.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandStatusCycleTest.java
Labels: documentation, enhancement, code-review, Build-success

#298 NonUniqueResultException 해결
  src/main/java/com/server/EZY/model/plan/errand/repository/errand/ErrandCustomRepositoryImpl.java
Labels: code-review, hotfix, Build-success

#297 Fix Transactional 누락
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
Labels: code-review, hotfix, Build-success

#299 Develop
  src/main/java/com/server/EZY/model/plan/errand/ErrandEntity.java
  src/main/java/com/server/EZY/model/plan/errand/controller/ErrandController.java
  src/main/java/com/server/EZY/model/plan/errand/dto/ErrandResponseDto.java
  src/main/java/com/server/EZY/model/plan/errand/dto/ErrandSetDto.java
  src/main/java/com/server/EZY/model/plan/errand/repository/errand/ErrandCustomRepository.java
  src/main/java/com/server/EZY/model/plan/errand/repository/errand/ErrandCustomRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/errand/repository/errand_detail/ErrandDetailRepository.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandService.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/main/java/com/server/EZY/model/plan/personal/controller/PersonalPlanController.java
  src/main/java/com/server/EZY/model/plan/personal/dto/PersonalPlanDto.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanCustomRepository.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanCustomRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImpl.java
  src/main/java/com/server/EZY/model/plan/personal/service/strategy/PersonalPlanStrategyImpl.java
  src/test/java/com/server/EZY/model/plan/errand/ErrandTest.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandServiceImplTest.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandStatusCycleTest.java
  src/test/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImplTest.java
Labels: enhancement, Urgent, Build-success

#301 Develop
  build.gradle
  src/main/java/com/server/EZY/config/message/MessageConfiguration.java
  src/main/java/com/server/EZY/dummy_for_dev/GenerateMemberAccount.java
  src/main/java/com/server/EZY/exception/authentication_number/AuthenticationNumberExceptionHandler.java
  src/main/java/com/server/EZY/exception/authentication_number/AuthenticationNumberExceptionHandlerImpl.java
  src/main/java/com/server/EZY/exception/authentication_number/controller/AuthenticationNumberExceptionController.java
  src/main/java/com/server/EZY/exception/authentication_number/exception/AuthenticationNumberTransferFailedException.java
  src/main/java/com/server/EZY/exception/authentication_number/exception/FailedToSendMessageException.java
  src/main/java/com/server/EZY/exception/fcm_push/FcmPushFailException.java
  src/main/java/com/server/EZY/model/member/service/message/MessageServiceImpl.java
  src/main/java/com/server/EZY/model/plan/errand/ErrandEntity.java
  src/main/java/com/server/EZY/model/plan/errand/controller/ErrandController.java
  src/main/java/com/server/EZY/model/plan/errand/controller/ErrandStatusCycleController.java
  src/main/java/com/server/EZY/model/plan/errand/dto/ErrandResponseDto.java
  src/main/java/com/server/EZY/model/plan/errand/dto/ErrandSetDto.java
  src/main/java/com/server/EZY/model/plan/errand/repository/errand/ErrandCustomRepository.java
  src/main/java/com/server/EZY/model/plan/errand/repository/errand/ErrandCustomRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/errand/repository/errand_detail/ErrandDetailRepository.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandService.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/main/java/com/server/EZY/model/plan/personal/controller/PersonalPlanController.java
  src/main/java/com/server/EZY/model/plan/personal/dto/PersonalPlanDto.java
  src/main/java/com/server/EZY/model/plan/personal/dto/PersonalPlanSetDto.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanCustomRepository.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanCustomRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepository.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepositoryCustom.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImpl.java
  src/main/java/com/server/EZY/model/plan/personal/service/strategy/PersonalPlanStrategyImpl.java
  src/main/java/com/server/EZY/model/plan/tag/dto/TagSetDto.java
  src/main/java/com/server/EZY/notification/config/FirebaseMessagingConfig.java
  src/main/java/com/server/EZY/notification/dto/FcmSourceDto.java
  src/main/java/com/server/EZY/notification/enum_type/FcmActionSelector.java
  src/main/java/com/server/EZY/notification/enum_type/FcmRole.java
  src/main/java/com/server/EZY/notification/service/FirebaseMessagingService.java
  src/main/java/com/server/EZY/notification/service/feature/FcmActiveSender.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
  src/test/java/com/server/EZY/exception/AuthenticationNumberExceptionHandlerTest.java
  src/test/java/com/server/EZY/model/member/controller/MemberControllerTest.java
  src/test/java/com/server/EZY/model/member/service/MemberServiceTest.java
  src/test/java/com/server/EZY/model/plan/errand/ErrandTest.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandServiceImplTest.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandStatusCycleTest.java
  src/test/java/com/server/EZY/model/plan/personal/controller/PersonalPlanControllerTest.java
  src/test/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImplTest.java
  src/test/java/com/server/EZY/model/plan/tag/controller/TagControllerTest.java
  src/test/java/com/server/EZY/model/plan/tag/service/TagServiceImplTest.java
  src/test/java/com/server/EZY/notification/service/FirebaseMessagingServiceTest.java
  src/test/resources/application.yml
Labels: documentation, Build-success

#302 Feature/심부름 자세히 조회
  src/main/java/com/server/EZY/model/plan/errand/controller/ErrandController.java
  src/main/java/com/server/EZY/model/plan/errand/dto/ErrandResponseDto.java
  src/main/java/com/server/EZY/model/plan/errand/repository/errand/ErrandCustomRepository.java
  src/main/java/com/server/EZY/model/plan/errand/repository/errand/ErrandCustomRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandService.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandServiceImplTest.java
Labels: documentation, enhancement, code-review, Build-success

#300 태그 저장시 tagIdx반환
  src/main/java/com/server/EZY/model/plan/tag/controller/TagController.java
  src/main/java/com/server/EZY/model/plan/tag/dto/TagGetDto.java
Labels: code-review, Build-success

#303 Develop
  src/main/java/com/server/EZY/model/plan/errand/controller/ErrandController.java
  src/main/java/com/server/EZY/model/plan/errand/dto/ErrandResponseDto.java
  src/main/java/com/server/EZY/model/plan/errand/repository/errand/ErrandCustomRepository.java
  src/main/java/com/server/EZY/model/plan/errand/repository/errand/ErrandCustomRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandService.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/main/java/com/server/EZY/model/plan/tag/controller/TagController.java
  src/main/java/com/server/EZY/model/plan/tag/dto/TagGetDto.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandServiceImplTest.java
Labels: Build-success

#304 Refectoring
  src/main/java/com/server/EZY/util/CurrentUserUtil.java
Labels: hotfix, Urgent, Build-success

#307 Add sendErrand 에 exception 추가
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
Labels: documentation, enhancement

#308 Develop
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/main/java/com/server/EZY/util/CurrentUserUtil.java
Labels: hotfix, Urgent

#311 Feature/errand user available
  src/main/java/com/server/EZY/model/member/controller/MemberController.java
  src/main/java/com/server/EZY/model/member/dto/UsernameResponseDto.java
  src/main/java/com/server/EZY/model/member/repository/MemberCustomRepository.java
  src/main/java/com/server/EZY/model/member/repository/MemberCustomRepositoryImpl.java
  src/main/java/com/server/EZY/model/member/repository/MemberRepository.java
  src/main/java/com/server/EZY/model/member/service/MemberService.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/test/java/com/server/EZY/model/member/service/MemberServiceTest.java
Labels: documentation, enhancement, code-review, Build-success

#312 Develop
  Dockerfile
  Jenkinsfile
  docker-compose.yml
  src/main/java/com/server/EZY/model/member/controller/MemberController.java
  src/main/java/com/server/EZY/model/member/dto/UsernameResponseDto.java
  src/main/java/com/server/EZY/model/member/repository/MemberCustomRepository.java
  src/main/java/com/server/EZY/model/member/repository/MemberCustomRepositoryImpl.java
  src/main/java/com/server/EZY/model/member/repository/MemberRepository.java
  src/main/java/com/server/EZY/model/member/service/MemberService.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/test/java/com/server/EZY/model/member/service/MemberServiceTest.java
Labels: documentation, Build-success

#313 인증된 회원만 요청허용 설정
  src/main/java/com/server/EZY/security/SecurityConfig.java
Labels: Build-success

#314 API 주소에 슬래시 제거 [GET] /v1/errand/ -> /v1/errand
  src/main/java/com/server/EZY/model/plan/errand/controller/ErrandController.java
Labels: code-review, hotfix, Build-success
