Repository neulsom-EZY/EZY-server, pull requests merged in 2021-08, with the labels that each got.

#138 Feature/personal plan controller
  src/main/java/com/server/EZY/model/plan/personal/controller/PersonalPlanController.java
Labels: code-review, enhancement

#140 [ADD] @ApiImplicitParams, [UPDATE] about signup
  src/main/java/com/server/EZY/model/member/controller/CertifiedMemberController.java
  src/main/java/com/server/EZY/model/member/controller/MemberController.java
  src/main/java/com/server/EZY/model/member/controller/jwt/RefreshTokenController.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/test/java/com/server/EZY/model/member/service/MemberServiceTest.java
Labels: code-review

#143 exception로직 관련 가독성을 위한 class, 패키지 이름변경
  src/main/java/com/server/EZY/exception/authenticationNumber/AuthenticationNumberExceptionHandler.java
  src/main/java/com/server/EZY/exception/authenticationNumber/AuthenticationNumberExceptionHandlerImpl.java
  src/main/java/com/server/EZY/exception/customError/CustomErrorHandler.java
  src/main/java/com/server/EZY/exception/customError/CustomErrorHandlerImpl.java
  src/main/java/com/server/EZY/exception/token/TokenExceptionHandler.java
  src/main/java/com/server/EZY/exception/token/TokenExceptionHandlerImpl.java
  src/main/java/com/server/EZY/exception/unknownException/UnknownExceptionHandler.java
  src/main/java/com/server/EZY/exception/user/MemberExceptionHandler.java
  src/main/java/com/server/EZY/exception/user/MemberExceptionHandlerImpl.java
  src/test/java/com/server/EZY/exception/AuthenticationNumberExceptionHandlerTest.java
  src/test/java/com/server/EZY/exception/CustomErrorHandlerTest.java
  src/test/java/com/server/EZY/exception/MemberExceptionHandlerTest.java
  src/test/java/com/server/EZY/exception/TokenExceptionHandlerTest.java
  src/test/java/com/server/EZY/exception/UnknownExceptionHandlerTest.java
Labels: code-review

#145 Feature/errand save 비즈니스 로직 추가
  src/main/java/com/server/EZY/model/plan/errand/ErrandEntity.java
  src/main/java/com/server/EZY/model/plan/errand/dto/ErrandSetDto.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandService.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/test/java/com/server/EZY/model/plan/errand/ErrandTest.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandServiceImplTest.java
Labels: code-review, enhancement

#149 Exception헨들링 누락(405 해결)
  src/main/java/com/server/EZY/exception/unknownException/UnknownExceptionHandler.java
Labels: bug, hotfix

#152 개인일정조회 - startTime 만 requestParam 으로 넘겼을 때 조건 성공!
  src/main/java/com/server/EZY/model/plan/embeddedTypes/Period.java
  src/main/java/com/server/EZY/model/plan/personal/controller/PersonalPlanController.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepoCustom.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepoImpl.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepository.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImpl.java
Labels: code-review, enhancement

#150 BasicError(White Label Error) Handling 로직 처리방식 변경
  src/main/java/com/server/EZY/exception/basicError/BasicErrorHandler.java
  src/main/java/com/server/EZY/exception/basicError/controller/BasicErrorController.java
  src/main/java/com/server/EZY/exception/customError/CustomErrorHandler.java
  src/main/java/com/server/EZY/exception/customError/CustomErrorHandlerImpl.java
  src/main/java/com/server/EZY/exception/customError/controller/BasicErrorController.java
  src/main/java/com/server/EZY/exception/customError/controller/CustomExceptionController.java
  src/main/java/com/server/EZY/exception/customError/exception/CustomForbiddenException.java
  src/main/java/com/server/EZY/exception/customError/exception/CustomNotFoundException.java
  src/main/java/com/server/EZY/exception/customError/exception/CustomUnauthorizedException.java
  src/test/java/com/server/EZY/exception/CustomErrorHandlerTest.java
Labels: code-review

#153 Feature/base time entity field rename
  src/main/java/com/server/EZY/model/baseTime/BaseTimeEntity.java
Labels: code-review

#154 Feature/personal plan filter - [requestParam]
  src/main/java/com/server/EZY/model/plan/embeddedTypes/Period.java
  src/main/java/com/server/EZY/model/plan/personal/controller/PersonalPlanController.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepoCustom.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImpl.java
  src/test/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImplTest.java
Labels: Build-success, code-review, enhancement

#155 Develop
  src/main/java/com/server/EZY/exception/authenticationNumber/AuthenticationNumberExceptionHandler.java
  src/main/java/com/server/EZY/exception/authenticationNumber/AuthenticationNumberExceptionHandlerImpl.java
  src/main/java/com/server/EZY/exception/basicError/BasicErrorHandler.java
  src/main/java/com/server/EZY/exception/basicError/controller/BasicErrorController.java
  src/main/java/com/server/EZY/exception/customError/CustomErrorAdvice.java
  src/main/java/com/server/EZY/exception/customError/CustomErrorAdviceImpl.java
  src/main/java/com/server/EZY/exception/customError/controller/BasicErrorController.java
  src/main/java/com/server/EZY/exception/customError/controller/CustomExceptionController.java
  src/main/java/com/server/EZY/exception/customError/exception/CustomForbiddenException.java
  src/main/java/com/server/EZY/exception/customError/exception/CustomNotFoundException.java
  src/main/java/com/server/EZY/exception/customError/exception/CustomUnauthorizedException.java
  src/main/java/com/server/EZY/exception/token/TokenExceptionHandler.java
  src/main/java/com/server/EZY/exception/token/TokenExceptionHandlerImpl.java
  src/main/java/com/server/EZY/exception/unknownException/UnknownExceptionHandler.java
  src/main/java/com/server/EZY/exception/user/MemberExceptionHandler.java
  src/main/java/com/server/EZY/exception/user/MemberExceptionHandlerImpl.java
  src/main/java/com/server/EZY/model/baseTime/BaseTimeEntity.java
  src/main/java/com/server/EZY/model/member/dto/AuthDto.java
  src/main/java/com/server/EZY/model/member/dto/MemberDto.java
  src/main/java/com/server/EZY/model/member/dto/PasswordChangeDto.java
  src/main/java/com/server/EZY/model/member/dto/UsernameChangeDto.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/EZY/model/plan/embeddedTypes/Period.java
  src/main/java/com/server/EZY/model/plan/errand/ErrandEntity.java
  src/main/java/com/server/EZY/model/plan/errand/dto/ErrandSetDto.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandService.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/main/java/com/server/EZY/model/plan/personal/controller/PersonalPlanController.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepoCustom.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepoImpl.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepository.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImpl.java
  src/test/java/com/server/EZY/exception/AuthenticationNumberExceptionHandlerTest.java
  src/test/java/com/server/EZY/exception/CustomErrorAdviceTest.java
  src/test/java/com/server/EZY/exception/CustomErrorHandlerTest.java
  src/test/java/com/server/EZY/exception/MemberExceptionHandlerTest.java
  src/test/java/com/server/EZY/exception/TokenExceptionHandlerTest.java
  src/test/java/com/server/EZY/exception/UnknownExceptionHandlerTest.java
  src/test/java/com/server/EZY/model/member/controller/CertifiedMemberControllerTest.java
  src/test/java/com/server/EZY/model/member/controller/MemberControllerTest.java
  src/test/java/com/server/EZY/model/member/service/MemberServiceTest.java
  src/test/java/com/server/EZY/model/plan/errand/ErrandTest.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandServiceImplTest.java
  src/test/java/com/server/EZY/model/plan/personal/PersonalPlanEntityTest.java
  src/test/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImplTest.java
Labels: Build-success

#158 TagEntity에 Color추가
  src/main/java/com/server/EZY/model/plan/tag/TagEntity.java
  src/main/java/com/server/EZY/model/plan/tag/embeddedTypes/Color.java
Labels: code-review, Build-success

#159 [UPDATE] 전화번호 입력 시 회원이 아니여도 인증번호 발송
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
Labels: code-review, Incomplete, Build-success

#162 [UPDATE] change member service return value
  src/main/java/com/server/EZY/model/member/controller/CertifiedMemberController.java
  src/main/java/com/server/EZY/model/member/controller/MemberController.java
  src/main/java/com/server/EZY/model/member/service/MemberService.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/EZY/model/member/service/jwt/RefreshTokenService.java
  src/main/java/com/server/EZY/model/member/service/jwt/RefreshTokenServiceImpl.java
  src/test/java/com/server/EZY/model/member/controller/MemberControllerTest.java
  src/test/java/com/server/EZY/model/member/service/MemberServiceTest.java
Labels: documentation, code-review, Fix-todo

#161 Feature/tag save
  src/main/java/com/server/EZY/model/plan/tag/controller/TagController.java
  src/main/java/com/server/EZY/model/plan/tag/dto/TagSetDto.java
  src/main/java/com/server/EZY/model/plan/tag/service/TagService.java
  src/main/java/com/server/EZY/model/plan/tag/service/TagServiceImpl.java
  src/test/java/com/server/EZY/model/plan/tag/service/TagServiceImplTest.java
Labels: enhancement, code-review

#166 Feature/tag delete
  src/main/java/com/server/EZY/model/plan/tag/service/TagService.java
  src/main/java/com/server/EZY/model/plan/tag/service/TagServiceImpl.java
  src/test/java/com/server/EZY/model/plan/tag/service/TagServiceImplTest.java
Labels: enhancement, code-review, Urgent

#164 PersonalPlanEntity_생성_조회_삭제_테스트 실패 해결
  src/test/java/com/server/EZY/model/plan/personal/PersonalPlanEntityTest.java
Labels: bug, hotfix, Urgent, Incomplete

#160 PlanEntity의 PlanInfo에 location필드 추가
  src/main/java/com/server/EZY/model/plan/embeddedTypes/PlanInfo.java
Labels: bug, code-review, Fix-todo

#168 Hotfix
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandServiceImplTest.java
  src/test/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImplTest.java
Labels: bug, hotfix, Urgent

#167 Feature/tag select
  src/main/java/com/server/EZY/model/plan/tag/repository/TagRepository.java
  src/main/java/com/server/EZY/model/plan/tag/service/TagService.java
  src/main/java/com/server/EZY/model/plan/tag/service/TagServiceImpl.java
  src/test/java/com/server/EZY/model/plan/tag/service/TagServiceImplTest.java
Labels: enhancement, code-review, Build-success

#170 Entity에 Min Max 추가
  src/main/java/com/server/EZY/model/plan/tag/embeddedTypes/Color.java
Labels: Build-success

#171 [FIX] test code method naming
  src/test/java/com/server/EZY/model/member/controller/CertifiedMemberControllerTest.java
  src/test/java/com/server/EZY/model/member/service/MemberServiceTest.java
Labels: code-review

#173 repository, embeddedType 패키지의 하위 코드를 Jacoco테스트 커버리지에서 제외함
  build.gradle
Labels: code-review

#174 [FIX] Refresh Service Architecture
  src/main/java/com/server/EZY/model/member/controller/jwt/RefreshTokenController.java
  src/main/java/com/server/EZY/model/member/service/jwt/RefreshTokenService.java
  src/main/java/com/server/EZY/model/member/service/jwt/RefreshTokenServiceImpl.java
  src/main/java/com/server/EZY/security/SecurityConfig.java
  src/test/java/com/server/EZY/model/member/service/jwt/RefreshTokenServiceTest.java
Labels: code-review, Build-success

#175 [UPDATE] Logout Service
  src/main/java/com/server/EZY/model/member/controller/CertifiedMemberController.java
  src/main/java/com/server/EZY/model/member/service/MemberService.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/test/java/com/server/EZY/model/member/service/MemberServiceTest.java
Labels: code-review, Build-success

#176 패키지 네이밍 규칙에 따라 스네이크_케이스로 변경 후 이름 변경한 패키지들은 단수를 사용함
  src/main/java/com/server/EZY/exception/authentication_number/AuthenticationNumberExceptionHandler.java
  src/main/java/com/server/EZY/exception/authentication_number/AuthenticationNumberExceptionHandlerImpl.java
  src/main/java/com/server/EZY/exception/authentication_number/controller/AuthenticationNumberExceptionController.java
  src/main/java/com/server/EZY/exception/authentication_number/exception/AuthenticationNumberTransferFailedException.java
  src/main/java/com/server/EZY/exception/authentication_number/exception/InvalidAuthenticationNumberException.java
  src/main/java/com/server/EZY/exception/basic_error/BasicErrorHandler.java
  src/main/java/com/server/EZY/exception/basic_error/controller/BasicErrorController.java
  src/main/java/com/server/EZY/exception/invalidRequest_data/InvalidRequestDataHandler.java
  src/main/java/com/server/EZY/exception/unknown_exception/UnknownExceptionHandler.java
  src/main/java/com/server/EZY/model/base_time/BaseTimeEntity.java
  src/main/java/com/server/EZY/model/member/MemberEntity.java
  src/main/java/com/server/EZY/model/member/dto/AuthDto.java
  src/main/java/com/server/EZY/model/member/dto/MemberDto.java
  src/main/java/com/server/EZY/model/member/enum_type/Role.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/EZY/model/member/service/jwt/RefreshTokenServiceImpl.java
  src/main/java/com/server/EZY/model/plan/PlanEntity.java
  src/main/java/com/server/EZY/model/plan/embedded_type/Period.java
  src/main/java/com/server/EZY/model/plan/embedded_type/PlanInfo.java
  src/main/java/com/server/EZY/model/plan/errand/ErrandEntity.java
  src/main/java/com/server/EZY/model/plan/errand/ErrandStatusEntity.java
  src/main/java/com/server/EZY/model/plan/errand/dto/ErrandSetDto.java
  src/main/java/com/server/EZY/model/plan/errand/enum_type/ResponseStatus.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/main/java/com/server/EZY/model/plan/personal/PersonalPlanEntity.java
  src/main/java/com/server/EZY/model/plan/personal/dto/PersonalPlanSetDto.java
  src/main/java/com/server/EZY/model/plan/tag/TagEntity.java
  src/main/java/com/server/EZY/model/plan/tag/dto/TagSetDto.java
  src/main/java/com/server/EZY/model/plan/tag/embedded_type/Color.java
  src/main/java/com/server/EZY/security/SecurityConfig.java
  src/main/java/com/server/EZY/security/authentication/MyUserDetails.java
  src/main/java/com/server/EZY/security/jwt/JwtTokenProvider.java
  src/test/java/com/server/EZY/exception/AuthenticationNumberExceptionHandlerTest.java
  src/test/java/com/server/EZY/exception/UnknownExceptionHandlerTest.java
  src/test/java/com/server/EZY/model/member/MemberEntityTest.java
  src/test/java/com/server/EZY/model/member/service/MemberServiceTest.java
  src/test/java/com/server/EZY/model/member/service/jwt/RefreshTokenServiceTest.java
  src/test/java/com/server/EZY/model/plan/errand/ErrandTest.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandServiceImplTest.java
  src/test/java/com/server/EZY/model/plan/personal/PersonalPlanEntityTest.java
  src/test/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImplTest.java
  src/test/java/com/server/EZY/model/plan/tag/service/TagServiceImplTest.java
  src/test/java/com/server/EZY/security/SecurityTest.java
  src/test/java/com/server/EZY/security/authentication/MyUserDetailsTest.java
  src/test/java/com/server/EZY/util/CurrentUserUtilTest.java
Labels: code-review, Build-success

#177 Feature/personal plan controller test - save personalPlan
  build.gradle
  src/test/java/com/server/EZY/model/plan/personal/controller/PersonalPlanControllerTest.java
  src/test/java/com/server/EZY/testConfig/AbstractControllerTest.java
Labels: enhancement, code-review, Incomplete, Build-success

#178 myUserDetails Test 보완
  src/test/java/com/server/EZY/security/authentication/MyUserDetailsTest.java
Labels: code-review, Build-success

#179 [FIX] 패키지 이름 바뀌면서 import오류
  src/test/java/com/server/EZY/model/plan/personal/controller/PersonalPlanControllerTest.java
Labels: hotfix, Build-success

#181 [UPDATE] refresh service test 보완
  src/main/java/com/server/EZY/model/member/service/jwt/RefreshTokenServiceImpl.java
  src/test/java/com/server/EZY/model/member/service/jwt/RefreshTokenServiceTest.java
Labels: code-review, Build-success

#182 Feature/personal plan controller test
  src/test/java/com/server/EZY/model/plan/personal/controller/PersonalPlanControllerTest.java
Labels: question, code-review, Incomplete, Fix-todo

#184 Feature/tag controller
  src/main/java/com/server/EZY/model/plan/tag/controller/TagController.java
Labels: enhancement, code-review, Incomplete, Build-success

#186 Develop
  src/main/java/com/server/EZY/model/member/service/jwt/RefreshTokenServiceImpl.java
  src/main/java/com/server/EZY/model/plan/tag/controller/TagController.java
  src/test/java/com/server/EZY/model/member/service/jwt/RefreshTokenServiceTest.java
  src/test/java/com/server/EZY/model/plan/personal/controller/PersonalPlanControllerTest.java
  src/test/java/com/server/EZY/model/plan/tag/controller/TagControllerTest.java
Labels: Build-success

#187 [UPDATE] member service test
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/test/java/com/server/EZY/model/member/service/MemberServiceTest.java
Labels: code-review, Build-success

#188 Feature/apns initial setting
  build.gradle
  src/main/java/com/server/EZY/config/apns/ApnsConfig.java
  src/main/java/com/server/EZY/model/notification/apns/APNS.java
  src/main/java/com/server/EZY/model/notification/apns/controller/NotificationController.java
Labels: enhancement, Urgent, Fix-todo

#190 Delete about APNs package, setting class
  src/main/java/com/server/EZY/config/apns/ApnsConfig.java
  src/main/java/com/server/EZY/model/notification/apns/APNS.java
  src/main/java/com/server/EZY/model/notification/apns/controller/NotificationController.java
Labels: hotfix, Build-success

#189 Develop
  build.gradle
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/test/java/com/server/EZY/model/member/service/MemberServiceTest.java
Labels: Build-success
