Repository neulsom-EZY/EZY-server, pull requests merged in 2021-09, with the labels that each got.

#191 Feature/fcm push settings & feature - draft [Aug,30]
  .gitignore
  build.gradle
  src/main/java/com/server/EZY/notification/FcmMessage.java
  src/main/java/com/server/EZY/notification/config/FirebaseMessagingConfiguration.java
  src/main/java/com/server/EZY/notification/controller/NotificationController.java
  src/main/java/com/server/EZY/notification/service/FirebaseMessagingService.java
  src/main/java/com/server/EZY/notification/service/HeaderRequestInterceptor.java
  src/main/java/com/server/EZY/notification/service/IosPushNotificationsService.java
  src/main/resources/application.yml
  src/main/resources/firebase-service-account.json
Labels: documentation, enhancement, Incomplete, Build-success

#193 Feature/siwony tag select improvment
  src/main/java/com/server/EZY/EzyApplication.java
  src/main/java/com/server/EZY/model/plan/tag/dto/TagSetDto.java
  src/main/java/com/server/EZY/model/plan/tag/repository/TagRepoCustom.java
  src/main/java/com/server/EZY/model/plan/tag/repository/TagRepoImpl.java
  src/main/java/com/server/EZY/model/plan/tag/repository/TagRepository.java
  src/main/java/com/server/EZY/model/plan/tag/service/TagService.java
  src/main/java/com/server/EZY/model/plan/tag/service/TagServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/server/EZY/model/plan/tag/service/TagServiceImplTest.java
Labels: duplicate, Urgent, Incomplete, Fix-todo

#192 Feature/tag select improvement
  src/main/java/com/server/EZY/model/plan/tag/dto/TagGetDto.java
  src/main/java/com/server/EZY/model/plan/tag/dto/TagSetDto.java
  src/main/java/com/server/EZY/model/plan/tag/repository/TagRepoCustom.java
  src/main/java/com/server/EZY/model/plan/tag/repository/TagRepoImpl.java
  src/main/java/com/server/EZY/model/plan/tag/repository/TagRepository.java
  src/main/java/com/server/EZY/model/plan/tag/service/TagService.java
  src/main/java/com/server/EZY/model/plan/tag/service/TagServiceImpl.java
  src/test/java/com/server/EZY/model/plan/tag/service/TagServiceImplTest.java
Labels: documentation, help wanted, code-review, Incomplete, Build-success

#194 [solved] Feature/query improve
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepository.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepositoryCustom.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/tag/dto/TagGetDto.java
  src/main/java/com/server/EZY/model/plan/tag/repository/TagRepository.java
  src/main/java/com/server/EZY/model/plan/tag/repository/TagRepositoryCustom.java
  src/main/java/com/server/EZY/model/plan/tag/repository/TagRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/tag/service/TagServiceImpl.java
  src/test/java/com/server/EZY/model/plan/tag/service/TagServiceImplTest.java
Labels: code-review, hotfix, Urgent, Build-success

#195 Feature/add application yml
  .gitignore
  src/main/resources/application.yml
  src/main/resources/firebase-service-account.json
Labels: code-review, Urgent, Build-success

#196 Develop
  .gitignore
  build.gradle
  src/main/java/com/server/EZY/EzyApplication.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepository.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepositoryCustom.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/tag/dto/TagGetDto.java
  src/main/java/com/server/EZY/model/plan/tag/dto/TagSetDto.java
  src/main/java/com/server/EZY/model/plan/tag/repository/TagRepository.java
  src/main/java/com/server/EZY/model/plan/tag/repository/TagRepositoryCustom.java
  src/main/java/com/server/EZY/model/plan/tag/repository/TagRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/tag/service/TagService.java
  src/main/java/com/server/EZY/model/plan/tag/service/TagServiceImpl.java
  src/main/java/com/server/EZY/notification/FcmMessage.java
  src/main/java/com/server/EZY/notification/config/FirebaseMessagingConfiguration.java
  src/main/java/com/server/EZY/notification/controller/NotificationController.java
  src/main/java/com/server/EZY/notification/service/FirebaseMessagingService.java
  src/main/java/com/server/EZY/notification/service/HeaderRequestInterceptor.java
  src/main/java/com/server/EZY/notification/service/IosPushNotificationsService.java
  src/main/resources/application.yml
  src/test/java/com/server/EZY/model/plan/tag/service/TagServiceImplTest.java
Labels: Build-success

#198 회원 controller 수정
  src/main/java/com/server/EZY/model/member/controller/CertifiedMemberController.java
  src/main/java/com/server/EZY/model/member/controller/MemberController.java
  src/main/java/com/server/EZY/security/SecurityConfig.java
  src/test/java/com/server/EZY/model/member/controller/CertifiedMemberControllerTest.java
  src/test/java/com/server/EZY/model/member/controller/MemberControllerTest.java
Labels: Build-success

#197 로그인 로직 수정
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
Labels: code-review, Build-success

#199 Feature/fcm delete unused assets
  src/main/java/com/server/EZY/notification/FcmMessage.java
  src/main/java/com/server/EZY/notification/config/FirebaseMessagingConfiguration.java
  src/main/java/com/server/EZY/notification/service/FirebaseMessagingService.java
  src/main/java/com/server/EZY/notification/service/IosPushNotificationsService.java
Labels: documentation, code-review, Fix-todo

#200 [HOTFIX] Add iOS push noti service annotation to be able @Async func
  src/main/java/com/server/EZY/notification/service/IosPushNotificationsService.java
Labels: hotfix, Urgent, Build-success

#202 ResponseService, CommonResult 리펙토링
  src/main/java/com/server/EZY/exception/user/MemberExceptionHandlerImpl.java
  src/main/java/com/server/EZY/response/ResponseService.java
  src/main/java/com/server/EZY/response/result/CommonResult.java
  src/test/java/com/server/EZY/response/ResponseServiceTest.java
Labels: code-review, Build-success

#201 MessageConfiguration 주석 추가 및 패키지명 변경
  src/main/java/com/server/EZY/config/message/MessageConfiguration.java
Labels: question, code-review, Build-success

#203 MessageConfiguration속 method들에 @return 주석이 일관적이지 않는 설명 해결
  src/main/java/com/server/EZY/config/message/MessageConfiguration.java
Labels: code-review, Build-success

#205 Hotfix
  src/main/java/com/server/EZY/notification/config/FirebaseMessagingConfig.java
  src/main/java/com/server/EZY/notification/service/IosPushNotificationsService.java
Labels: hotfix, Urgent

#206 Develop
  src/main/java/com/server/EZY/config/message/MessageConfiguration.java
  src/main/java/com/server/EZY/exception/user/MemberExceptionHandlerImpl.java
  src/main/java/com/server/EZY/model/member/controller/CertifiedMemberController.java
  src/main/java/com/server/EZY/model/member/controller/MemberController.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/EZY/notification/FcmMessage.java
  src/main/java/com/server/EZY/notification/config/FirebaseMessagingConfig.java
  src/main/java/com/server/EZY/notification/config/FirebaseMessagingConfiguration.java
  src/main/java/com/server/EZY/notification/service/FirebaseMessagingService.java
  src/main/java/com/server/EZY/notification/service/IosPushNotificationsService.java
  src/main/java/com/server/EZY/response/ResponseService.java
  src/main/java/com/server/EZY/response/result/CommonResult.java
  src/main/java/com/server/EZY/security/SecurityConfig.java
  src/test/java/com/server/EZY/model/member/controller/CertifiedMemberControllerTest.java
  src/test/java/com/server/EZY/model/member/controller/MemberControllerTest.java
  src/test/java/com/server/EZY/response/ResponseServiceTest.java
Labels: documentation, Build-success

#207 전화번호 발급 후 api 연동
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/main/resources/application.yml
Labels: Build-success

#208 FIX Test/send fcm - 일부수정됨
  src/main/java/com/server/EZY/notification/FcmMessage.java
  src/main/java/com/server/EZY/notification/config/FirebaseMessagingConfig.java
  src/test/java/com/server/EZY/notification/config/FirebaseMessagingConfigTest.java
  src/test/java/com/server/EZY/notification/service/FirebaseMessagingServiceTest.java
Labels: documentation, code-review, Build-success, Fix-todo

#209 Update test with @qoxogus @siwony
  src/main/java/com/server/EZY/notification/config/FirebaseMessagingConfig.java
  src/test/java/com/server/EZY/notification/config/FirebaseMessagingConfigTest.java
Labels: bug, Fix-todo

#211 Update static method 에서 bean method 로 전환했습니다.
  src/main/java/com/server/EZY/notification/config/FirebaseMessagingConfig.java
  src/test/java/com/server/EZY/notification/config/FirebaseMessagingConfigTest.java
Labels: documentation, code-review, hotfix, Build-success

#212 Test/fcm
  src/main/java/com/server/EZY/notification/FcmMessage.java
  src/main/java/com/server/EZY/notification/service/FirebaseMessagingService.java
  src/main/java/com/server/EZY/notification/service/IosPushNotificationsService.java
  src/test/java/com/server/EZY/notification/config/FirebaseMessagingConfigTest.java
  src/test/java/com/server/EZY/notification/service/FirebaseMessagingServiceTest.java
Labels: code-review, Build-success

#213 Update 메시징 처리를 위한 FirebaseMessaging설정 후 Bean으로 등록하여 IoC가 관리하도록 함
  src/main/java/com/server/EZY/notification/config/FirebaseMessagingConfig.java
  src/main/java/com/server/EZY/notification/service/FirebaseMessagingService.java
  src/test/java/com/server/EZY/notification/service/FirebaseMessagingServiceTest.java
Labels: code-review, Build-success

#214 Delete MIT license
  LICENSE
Labels: hotfix, Urgent

#216 Update readme
  README.md
Labels: enhancement, Urgent

#217 Fix 최상위 예외인 Exception을 핸들링하는 핸들러의 우선순위를 매우 낮게 설정함
  src/main/java/com/server/EZY/exception/unknown_exception/UnknownExceptionHandler.java
Labels: code-review, hotfix, Urgent, Build-success

#218 FCM 푸시알람 성공
  src/main/java/com/server/EZY/notification/config/FirebaseMessagingConfig.java
  src/main/java/com/server/EZY/notification/service/FirebaseMessagingService.java
  src/main/java/com/server/EZY/notification/service/HeaderRequestInterceptor.java
  src/main/java/com/server/EZY/notification/service/IosPushNotificationsService.java
  src/test/java/com/server/EZY/notification/config/FirebaseMessagingConfigTest.java
  src/test/java/com/server/EZY/notification/service/FirebaseMessagingServiceTest.java
Labels: code-review, Build-success

#219 일부 테스트 코드에서 발생하던 IllegalStateException해결
  build.gradle
  src/main/java/com/server/EZY/notification/config/FirebaseMessagingConfig.java
  src/main/java/com/server/EZY/notification/service/FirebaseMessagingService.java
Labels: code-review, Build-success

#221 회원가입/로그인 fcm token 관련 로직 추가
  src/main/java/com/server/EZY/model/member/MemberEntity.java
  src/main/java/com/server/EZY/model/member/dto/AuthDto.java
  src/main/java/com/server/EZY/model/member/dto/MemberDto.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
Labels: code-review, Build-success

#222 Rename ResponseStatus -> ErrandResponseStatus
  src/main/java/com/server/EZY/model/plan/errand/ErrandStatusEntity.java
  src/main/java/com/server/EZY/model/plan/errand/enum_type/ErrandResponseStatus.java
  src/main/java/com/server/EZY/model/plan/errand/enum_type/ResponseStatus.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/test/java/com/server/EZY/model/plan/errand/ErrandTest.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandServiceImplTest.java
Labels: code-review, Build-success

#223 Update EZY 단일건 push 발송 성공
  src/test/java/com/server/EZY/notification/service/FirebaseMessagingServiceTest.java
Labels: Urgent

#224 Update token 다중 기기 전송 성공
  src/test/java/com/server/EZY/notification/service/FirebaseMessagingServiceTest.java
Labels: Urgent

#225 Develop
  build.gradle
  src/main/java/com/server/EZY/config/web/WebConfig.java
  src/main/java/com/server/EZY/exception/unknown_exception/UnknownExceptionHandler.java
  src/main/java/com/server/EZY/model/member/MemberEntity.java
  src/main/java/com/server/EZY/model/member/controller/CertifiedMemberController.java
  src/main/java/com/server/EZY/model/member/controller/MemberController.java
  src/main/java/com/server/EZY/model/member/controller/jwt/RefreshTokenController.java
  src/main/java/com/server/EZY/model/member/dto/AuthDto.java
  src/main/java/com/server/EZY/model/member/dto/MemberDto.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/EZY/model/plan/errand/ErrandStatusEntity.java
  src/main/java/com/server/EZY/model/plan/errand/enum_type/ErrandResponseStatus.java
  src/main/java/com/server/EZY/model/plan/errand/enum_type/ResponseStatus.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/main/java/com/server/EZY/notification/FcmMessage.java
  src/main/java/com/server/EZY/notification/config/FirebaseMessagingConfig.java
  src/main/java/com/server/EZY/notification/service/FirebaseMessagingService.java
  src/main/java/com/server/EZY/notification/service/HeaderRequestInterceptor.java
  src/main/java/com/server/EZY/notification/service/IosPushNotificationsService.java
  src/main/resources/application.yml
  src/test/java/com/server/EZY/model/member/controller/CertifiedMemberControllerTest.java
  src/test/java/com/server/EZY/model/member/controller/MemberControllerTest.java
  src/test/java/com/server/EZY/model/plan/errand/ErrandTest.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandServiceImplTest.java
  src/test/java/com/server/EZY/notification/service/FirebaseMessagingServiceTest.java
Labels: Build-success

#226 Add delete-merged-branch-bot config
  .github/delete-merged-branch-config.yml
Labels: hotfix, Urgent

#227 Hotfix exclude properties
  .github/delete-merged-branch-config.yml
Labels: hotfix, Urgent

#228 Delete branch bot config
  .github/delete-merged-branch-config.yml
Labels: hotfix, Urgent
