Repository neulsom-EZY/EZY-server, pull requests merged in 2021-10, with the labels that each got.

#232 Feature/fcm async method rollback
  src/main/java/com/server/EZY/notification/config/FirebaseMessagingConfig.java
  src/main/java/com/server/EZY/notification/service/HeaderRequestInterceptor.java
  src/main/java/com/server/EZY/notification/service/IosPushNotificationsService.java
Labels: Urgent, Build-success

#231 Feature/errand save service
  src/main/java/com/server/EZY/model/plan/errand/controller/ErrandController.java
  src/main/java/com/server/EZY/model/plan/errand/enum_type/ErrandRole.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandService.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/main/java/com/server/EZY/notification/service/FirebaseMessagingService.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandServiceImplTest.java
Labels: enhancement, code-review, Build-success

#233 fcmToken 변경 로직 로그인 로직과 분리
  src/main/java/com/server/EZY/model/member/controller/CertifiedMemberController.java
  src/main/java/com/server/EZY/model/member/dto/AuthDto.java
  src/main/java/com/server/EZY/model/member/dto/FcmTokenDto.java
  src/main/java/com/server/EZY/model/member/dto/MemberDto.java
  src/main/java/com/server/EZY/model/member/dto/PasswordChangeDto.java
  src/main/java/com/server/EZY/model/member/service/MemberService.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/EZY/security/SecurityConfig.java
  src/test/java/com/server/EZY/model/member/service/MemberServiceTest.java
Labels: code-review, Build-success

#235 FCM push 알람에 payloads를 추가할 수 있게 로직추가
  src/main/java/com/server/EZY/notification/FcmMessage.java
  src/main/java/com/server/EZY/notification/service/FirebaseMessagingService.java
Labels: code-review, Build-success

#236 FCM 푸시 알람을 비동기로 처리하는 로직 복구
  src/main/java/com/server/EZY/notification/service/FirebaseMessagingService.java
Labels: code-review, Build-success

#234 about member
  src/main/java/com/server/EZY/model/member/controller/CertifiedMemberController.java
  src/main/java/com/server/EZY/model/member/controller/MemberController.java
  src/main/java/com/server/EZY/model/member/dto/PhoneNumberChangeDto.java
  src/main/java/com/server/EZY/model/member/service/MemberService.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/EZY/model/member/service/jwt/RefreshTokenServiceImpl.java
  src/test/java/com/server/EZY/model/member/controller/CertifiedMemberControllerTest.java
  src/test/java/com/server/EZY/model/member/controller/MemberControllerTest.java
  src/test/java/com/server/EZY/model/member/service/MemberServiceTest.java
Labels: Build-success

#241 fcmToken 변경 컨트롤러 mapping 수정
  src/main/java/com/server/EZY/model/member/controller/CertifiedMemberController.java
Labels: Build-success

#240 Entity 점검 및 주석 추가
  src/main/java/com/server/EZY/model/base_time/BaseTimeEntity.java
  src/main/java/com/server/EZY/model/member/MemberEntity.java
  src/main/java/com/server/EZY/model/plan/PlanEntity.java
  src/main/java/com/server/EZY/model/plan/embedded_type/Period.java
  src/main/java/com/server/EZY/model/plan/embedded_type/PlanInfo.java
  src/main/java/com/server/EZY/model/plan/errand/ErrandEntity.java
  src/main/java/com/server/EZY/model/plan/errand/ErrandStatusEntity.java
  src/main/java/com/server/EZY/model/plan/personal/PersonalPlanEntity.java
  src/main/java/com/server/EZY/model/plan/tag/TagEntity.java
Labels: code-review, Build-success

#244 application.yml의 테스트 환경과 개발 환경의 분리
  src/main/java/com/server/EZY/config/swagger/SwaggerConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: code-review, Build-success

#243 인증번호 API 관련 Query Param Dto로 변경
  src/main/java/com/server/EZY/model/member/controller/MemberController.java
  src/main/java/com/server/EZY/model/member/dto/KeyDto.java
  src/main/java/com/server/EZY/model/member/dto/PhoneNumberDto.java
Labels: Build-success

#245 Jenkins 로 EC2 테스팅서버 CI/CD 적용완료
  Dockerfile
  Jenkinsfile
Labels: Urgent, Build-success

#247 문자로 username보내기 (username찾기)
  src/main/java/com/server/EZY/model/member/controller/MemberController.java
  src/main/java/com/server/EZY/model/member/service/MemberService.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/EZY/model/member/service/jwt/RefreshTokenServiceImpl.java
  src/main/java/com/server/EZY/model/member/service/message/MessageService.java
  src/main/java/com/server/EZY/model/member/service/message/MessageServiceImpl.java
  src/main/java/com/server/EZY/security/SecurityConfig.java
Labels: enhancement, code-review, Build-success

#251 Feature/expired jwt exception handling
  src/main/java/com/server/EZY/exception/token/TokenExceptionHandler.java
  src/main/java/com/server/EZY/exception/token/TokenExceptionHandlerImpl.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
  src/test/java/com/server/EZY/exception/TokenExceptionHandlerTest.java
Labels: code-review, Build-success

#256 Hotfix
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/main/java/com/server/EZY/notification/service/feature/ActiveFcmFilterService.java
Labels: documentation, enhancement, code-review, hotfix

#259 전화번호 중복 여부 확인
  src/main/java/com/server/EZY/model/member/controller/MemberController.java
  src/main/java/com/server/EZY/model/member/repository/MemberRepository.java
  src/main/java/com/server/EZY/model/member/service/MemberService.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/EZY/security/SecurityConfig.java
  src/test/java/com/server/EZY/model/member/service/MemberServiceTest.java
Labels: enhancement, code-review, Build-success

#266 Hotfix
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/main/java/com/server/EZY/notification/service/feature/FcmActiveSender.java
  src/main/java/com/server/EZY/notification/service/feature/FcmMakerService.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandServiceImplTest.java
Labels: bug, code-review, hotfix

#268 hotfix conflict로 인한 오류 해결
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/main/java/com/server/EZY/notification/service/feature/FcmActiveSender.java
Labels: bug, hotfix

#269 member dto access level
  src/main/java/com/server/EZY/model/member/dto/AuthDto.java
  src/main/java/com/server/EZY/model/member/dto/MemberDto.java
  src/main/java/com/server/EZY/model/member/dto/PhoneNumberChangeDto.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/test/java/com/server/EZY/security/SecurityTest.java
Labels: Build-success

#273 ADD AccessDenied, Authentication Entry Point
  src/main/java/com/server/EZY/security/SecurityConfig.java
  src/main/java/com/server/EZY/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/server/EZY/security/handler/CustomAuthenticationEntryPointHandler.java
Labels: enhancement, code-review, Build-success

#274 심부름 수락/거절 NPE해결
  src/main/java/com/server/EZY/model/plan/errand/ErrandStatusEntity.java
  src/main/java/com/server/EZY/model/plan/errand/repository/errand/ErrandCustomRepositoryImpl.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandAcceptRefuseTest.java
Labels: code-review, Build-success

#275 Rename ErrandStautsEntity -> ErrandDetailEntity
  src/main/java/com/server/EZY/model/plan/errand/ErrandDetailEntity.java
  src/main/java/com/server/EZY/model/plan/errand/ErrandEntity.java
  src/main/java/com/server/EZY/model/plan/errand/dto/ErrandSetDto.java
  src/main/java/com/server/EZY/model/plan/errand/repository/errand/ErrandCustomRepository.java
  src/main/java/com/server/EZY/model/plan/errand/repository/errand/ErrandCustomRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/errand/repository/errand_status/ErrandStatusRepository.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/test/java/com/server/EZY/model/plan/errand/ErrandTest.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandAcceptRefuseTest.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandServiceImplTest.java
Labels: code-review, Build-success

#276 심부름 읽음 기능 제거
  src/main/java/com/server/EZY/model/plan/errand/ErrandDetailEntity.java
  src/main/java/com/server/EZY/model/plan/errand/controller/ErrandStatusCycleController.java
  src/main/java/com/server/EZY/model/plan/errand/enum_type/ErrandResponseStatus.java
  src/main/java/com/server/EZY/model/plan/errand/enum_type/ErrandStatus.java
  src/main/java/com/server/EZY/model/plan/errand/service/ErrandServiceImpl.java
  src/test/java/com/server/EZY/model/plan/errand/ErrandTest.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandAcceptRefuseTest.java
  src/test/java/com/server/EZY/model/plan/errand/service/ErrandServiceImplTest.java
Labels: code-review, Build-success
