Repository neulsom-EZY/EZY-server, pull requests merged in 2021-06, with the labels that each got.

#17 Feature/entity modelling
  src/main/java/com/server/EZY/model/plan/PlanDType.java
  src/main/java/com/server/EZY/model/plan/PlanEntity.java
  src/main/java/com/server/EZY/model/plan/errand/ErrandEntity.java
  src/main/java/com/server/EZY/model/plan/personal/PersonalPlanEntity.java
  src/main/java/com/server/EZY/model/plan/team/TeamEntity.java
  src/main/java/com/server/EZY/model/plan/team/TeamPlanEntity.java
  src/main/java/com/server/EZY/model/plan/team/UserTeamEntity.java
  src/main/java/com/server/EZY/model/user/Role.java
  src/main/java/com/server/EZY/model/user/UserEntity.java
  src/main/java/com/server/EZY/repository/RepoTest.java
  src/main/java/com/server/EZY/repository/plan/ErrandRepository.java
  src/main/java/com/server/EZY/repository/plan/PersonalPlanRepository.java
  src/main/java/com/server/EZY/repository/plan/PlanRepository.java
  src/main/java/com/server/EZY/repository/plan/TeamPlanRepository.java
  src/main/java/com/server/EZY/repository/user/UserRepository.java
  src/main/java/com/server/EZY/security/JwtTokenProvider.java
  src/test/java/com/server/EZY/model/plan/PlanEntityTest.java
  src/test/java/com/server/EZY/model/plan/personal/PersonalPlanEntityTest.java
  src/test/java/com/server/EZY/model/user/UserEntityTest.java
Labels: help wanted, wontfix

#26 Feature/settings
  .gitignore
  build.gradle
  src/main/resources/application.yml
Labels: enhancement

#16 Feature/jwt
  src/main/java/com/server/EZY/controller/UserController.java
  src/main/java/com/server/EZY/dto/UserDto.java
  src/main/java/com/server/EZY/model/user/UserEntity.java
  src/main/java/com/server/EZY/repository/user/UserRepository.java
  src/main/java/com/server/EZY/security/MyUserDetails.java
  src/main/java/com/server/EZY/service/ServiceTest.java
  src/main/java/com/server/EZY/service/UserService.java
  src/test/java/com/server/EZY/EzyApplicationTests.java
Labels: code-review

#36 Hotfix
  build.gradle
  src/main/java/com/server/EZY/security/JwtTokenProvider.java
Labels: bug, code-review, hotfix

#38 Feature/jacoco
  build.gradle
  lombok.config
Labels: code-review

#40 Feature/entity modelling - 중간 점검 부탁드립니다.
  src/main/java/com/server/EZY/model/plan/PlanEntity.java
  src/main/java/com/server/EZY/model/plan/personal/PersonalPlanEntity.java
  src/main/java/com/server/EZY/model/plan/team/TeamPlanEntity.java
  src/main/java/com/server/EZY/repository/plan/PlanRepository.java
  src/main/resources/application.yml
  src/test/java/com/server/EZY/model/plan/PlanEntityTest.java
  src/test/java/com/server/EZY/model/plan/personal/PersonalPlanEntityTest.java
  src/test/java/com/server/EZY/model/plan/team/TeamPlanEntityTest.java
  src/test/java/com/server/EZY/model/user/UserEntityTest.java
Labels: code-review

#43 Feature/entity modelling
  src/main/java/com/server/EZY/dto/PersonalPlanUpdateDto.java
  src/main/java/com/server/EZY/dto/TeamPlanUpdateDto.java
  src/main/java/com/server/EZY/model/plan/PlanEntity.java
  src/main/java/com/server/EZY/model/plan/personal/PersonalPlanEntity.java
  src/main/java/com/server/EZY/model/plan/team/TeamPlanEntity.java
  src/main/java/com/server/EZY/model/user/UserEntity.java
  src/test/java/com/server/EZY/model/plan/PlanEntityTest.java
  src/test/java/com/server/EZY/model/plan/personal/PersonalPlanEntityTest.java
  src/test/java/com/server/EZY/model/plan/team/TeamPlanEntityTest.java
Labels: code-review

#45 Feature/user service
  src/main/java/com/server/EZY/model/plan/personal/dto/PersonalPlanDto.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepository.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/main/java/com/server/EZY/model/user/service/UserService.java
  src/test/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceTest.java
Labels: code-review, enhancement

#46 Feature/jwt comment
  src/main/java/com/server/EZY/model/user/controller/UserController.java
  src/main/java/com/server/EZY/model/user/service/jwt/RefreshTokenService.java
  src/main/java/com/server/EZY/security/jwt/JwtTokenProvider.java
Labels: code-review

#49 Feature/personal plan logic
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/main/java/com/server/EZY/model/user/service/UserServiceImpl.java
  src/test/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceTest.java
  src/test/java/com/server/EZY/model/user/UserEntityTest.java
Labels: code-review

#50 Feature/user
  src/main/java/com/server/EZY/model/user/controller/CertifiedUserController.java
  src/main/java/com/server/EZY/model/user/controller/UserController.java
  src/main/java/com/server/EZY/model/user/dto/PasswordChangeDto.java
  src/main/java/com/server/EZY/model/user/dto/PhoneNumberDto.java
  src/main/java/com/server/EZY/model/user/dto/WithdrawalDto.java
  src/main/java/com/server/EZY/model/user/service/UserServiceImpl.java
  src/test/java/com/server/EZY/model/user/controller/CertifiedUserControllerTest.java
  src/test/java/com/server/EZY/model/user/controller/UserControllerTest.java
  src/test/java/com/server/EZY/model/user/service/UserServiceTest.java
Labels: code-review, duplicate

#52 [ADD] test code - user
  src/main/java/com/server/EZY/model/user/dto/WithdrawalDto.java
  src/test/java/com/server/EZY/model/user/controller/CertifiedUserControllerTest.java
  src/test/java/com/server/EZY/model/user/controller/UserControllerTest.java
  src/test/java/com/server/EZY/model/user/service/UserServiceTest.java
Labels: code-review, help wanted

#53 Feature/entity modelling
  src/main/java/com/server/EZY/model/plan/errand/ErrandEntity.java
  src/main/java/com/server/EZY/model/plan/errand/dto/ErrandUpdateDto.java
  src/main/java/com/server/EZY/model/plan/plan/PlanEntity.java
  src/main/java/com/server/EZY/model/user/UserEntity.java
  src/test/java/com/server/EZY/model/plan/errand/ErrandEntityTest.java
Labels: code-review

#54 Feature/personal plan logic
  build.gradle
  src/main/java/com/server/EZY/config/querydsl/QuerydslConfiguration.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PlanRepositoryCustom.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PlanRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/main/java/com/server/EZY/model/plan/plan/repository/PlanRepository.java
  src/test/java/com/server/EZY/model/plan/personal/repository/PlanRepositorySupportTest.java
Labels: code-review

#56 Feature/personal plan logic
  src/main/java/com/server/EZY/model/plan/personal/repository/PlanRepositoryCustom.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PlanRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/test/java/com/server/EZY/model/plan/personal/repository/PlanRepositorySupportTest.java
Labels: code-review, question

#57 Feature/user - user
  src/main/java/com/server/EZY/model/user/controller/CertifiedUserController.java
  src/main/java/com/server/EZY/model/user/controller/UserController.java
  src/main/java/com/server/EZY/model/user/service/UserService.java
  src/main/java/com/server/EZY/model/user/service/UserServiceImpl.java
Labels: code-review

#58 [FIX] #55번 이슈 해결
  src/main/java/com/server/EZY/model/plan/plan/PlanEntity.java
Labels: bug, code-review, hotfix

#59 Feature/personal plan logic
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/test/java/com/server/EZY/model/plan/personal/repository/PlanRepositorySupportTest.java
Labels: code-review

#61 [UPDATE] currentUser Util
  src/main/java/com/server/EZY/model/user/service/UserServiceImpl.java
  src/main/java/com/server/EZY/model/user/util/CurrentUserUtil.java
  src/test/java/com/server/EZY/model/user/service/UserServiceTest.java
Labels: code-review
