Repository neulsom-EZY/EZY-server, pull requests merged in 2021-07, with the labels that each got.

#65 Feature/personal plan logic
  src/main/java/com/server/EZY/model/plan/personal/repository/PlanRepositoryCustom.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PlanRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/test/java/com/server/EZY/model/plan/personal/repository/PlanRepositorySupportTest.java
  src/test/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceTest.java
Labels: code-review

#70 Feature/team plan
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/main/java/com/server/EZY/model/plan/team/dto/TeamPlanDto.java
  src/main/java/com/server/EZY/model/plan/team/repository/TeamPlanRepository.java
  src/main/java/com/server/EZY/model/plan/team/service/TeamPlanService.java
  src/test/java/com/server/EZY/model/plan/team/service/TeamPlanServiceTest.java
Labels: code-review, help wanted

#71 Feature/custom exception
  build.gradle
  src/main/java/com/server/EZY/config/exception/MessageConfiguration.java
  src/main/java/com/server/EZY/exception/ExceptionAdvice.java
  src/main/java/com/server/EZY/exception/ExceptionAdviceImpl.java
  src/main/java/com/server/EZY/exception/token/TokenExceptionController.java
  src/main/java/com/server/EZY/exception/token/exception/AccessTokenExpiredException.java
  src/main/java/com/server/EZY/exception/token/exception/InvalidTokenException.java
  src/main/java/com/server/EZY/exception/unknown/UnKnownExceptionController.java
  src/main/java/com/server/EZY/exception/user/UserExceptionController.java
  src/main/java/com/server/EZY/exception/user/exception/UserNotFoundException.java
  src/main/java/com/server/EZY/model/user/service/UserServiceImpl.java
  src/main/java/com/server/EZY/response/ResponseService.java
  src/main/java/com/server/EZY/response/result/CommonResult.java
  src/main/java/com/server/EZY/response/result/ListResult.java
  src/main/java/com/server/EZY/response/result/SingleResult.java
  src/main/java/com/server/EZY/security/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
  src/test/java/com/server/EZY/exception/ExceptionAdviceTest.java
Labels: code-review

#73 Feature/team plan
  src/main/java/com/server/EZY/model/plan/headOfPlan/repository/HeadOfPlanRepository.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepositoryCustom.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/team/repository/TeamPlanRepositoryCustom.java
  src/main/java/com/server/EZY/model/plan/team/repository/TeamRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/team/service/TeamPlanService.java
  src/test/java/com/server/EZY/model/plan/team/service/TeamPlanServiceTest.java
Labels: code-review

#78 Feature/user
  src/test/java/com/server/EZY/model/user/util/CurrentUserUtilTest.java
Labels: code-review

#80 Feature/team plan
  src/main/java/com/server/EZY/model/plan/team/repository/TeamPlanRepositoryCustom.java
  src/main/java/com/server/EZY/model/plan/team/repository/TeamRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/team/service/TeamPlanService.java
  src/test/java/com/server/EZY/model/plan/HeadOfPlanEntityTest.java
  src/test/java/com/server/EZY/model/plan/personal/PersonalHeadOfPlanEntityTest.java
  src/test/java/com/server/EZY/model/plan/personal/repository/HeadOfPlanRepositorySupportTest.java
  src/test/java/com/server/EZY/model/plan/team/TeamHeadOfPlanEntityTest.java
  src/test/java/com/server/EZY/model/plan/team/service/TeamPlanServiceTest.java
Labels: bug, code-review

#79 [FIX] HeadOfPlanEntity의 생성자의 인자의 위치가 변경됨으로써 컴파일 오류 해결
  src/test/java/com/server/EZY/model/plan/HeadOfPlanEntityTest.java
  src/test/java/com/server/EZY/model/plan/personal/PersonalHeadOfPlanEntityTest.java
  src/test/java/com/server/EZY/model/plan/personal/repository/HeadOfPlanRepositorySupportTest.java
  src/test/java/com/server/EZY/model/plan/team/service/TeamPlanServiceTest.java
Labels: bug, code-review

#81 Feature/custom exception
  src/main/java/com/server/EZY/exception/ExceptionAdvice.java
  src/main/java/com/server/EZY/exception/ExceptionAdviceImpl.java
  src/main/java/com/server/EZY/exception/customError/BasicErrorController.java
  src/main/java/com/server/EZY/exception/customError/CustomExceptionController.java
  src/main/java/com/server/EZY/exception/customError/exception/CustomForbiddenException.java
  src/main/java/com/server/EZY/exception/customError/exception/CustomNotFoundException.java
  src/main/java/com/server/EZY/exception/customError/exception/CustomUnauthorizedException.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
  src/test/java/com/server/EZY/exception/ExceptionAdviceTest.java
Labels: code-review

#86 [FIX] change way CurrentUserUtil
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/main/java/com/server/EZY/model/plan/team/service/TeamPlanService.java
  src/main/java/com/server/EZY/util/CurrentUserUtil.java
  src/test/java/com/server/EZY/model/plan/team/service/TeamPlanServiceTest.java
  src/test/java/com/server/EZY/model/user/service/UserServiceTest.java
  src/test/java/com/server/EZY/util/CurrentUserUtilTest.java
Labels: help wanted

#87 Feature/team plan
  src/test/java/com/server/EZY/model/plan/team/service/TeamPlanServiceTest.java
  src/test/java/com/server/EZY/util/CurrentUserUtilTest.java
Labels: bug, hotfix

#97 Feature/jpa auditing
  src/main/java/com/server/EZY/EzyApplication.java
  src/main/java/com/server/EZY/model/baseTime/BaseTimeEntity.java
  src/test/java/com/server/EZY/EzyApplicationTests.java
Labels: code-review

#94 Feature/users
  .gitignore
  build.gradle
  src/main/java/com/server/EZY/model/user/controller/CertifiedUserController.java
  src/main/java/com/server/EZY/model/user/controller/UserController.java
  src/main/java/com/server/EZY/model/user/service/UserService.java
  src/main/java/com/server/EZY/model/user/service/UserServiceImpl.java
  src/main/java/com/server/EZY/security/SecurityConfig.java
  src/main/java/com/server/EZY/util/KeyUtil.java
  src/main/resources/application.yml
  src/test/java/com/server/EZY/model/user/service/UserServiceTest.java
  src/test/java/com/server/EZY/util/KeyUtilTest.java
Labels: code-review

#93 Feature/head of plan service
  src/main/java/com/server/EZY/model/plan/headOfPlan/repository/HOPRepositoryCustom.java
  src/main/java/com/server/EZY/model/plan/headOfPlan/repository/HOPRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/headOfPlan/repository/HeadOfPlanRepository.java
  src/main/java/com/server/EZY/model/plan/headOfPlan/service/HeadOfPlanService.java
  src/test/java/com/server/EZY/model/plan/headOfPlan/service/HeadOfPlanServiceTest.java
Labels: invalid

#95 Feature/new personal plan entity
  src/main/java/com/server/EZY/model/plan/Period.java
  src/main/java/com/server/EZY/model/plan/PlanInfo.java
  src/main/java/com/server/EZY/model/plan/errand/ErrandStatus.java
  src/main/java/com/server/EZY/model/plan/headOfPlan/enumType/PlanDType.java
  src/main/java/com/server/EZY/model/plan/personal/NewPersonalPlanEntity.java
  src/main/java/com/server/EZY/model/plan/personal/dto/NewPersonalPlanUpdateDto.java
  src/main/java/com/server/EZY/model/plan/personal/repository/NewPersonalPlanRepository.java
  src/main/java/com/server/EZY/model/plan/tag/TagEntity.java
  src/main/java/com/server/EZY/model/user/UserEntity.java
  src/test/java/com/server/EZY/model/plan/personal/PersonalHeadOfPlanEntityTest.java
  src/test/java/com/server/EZY/model/plan/personal/PersonalPlanEntityTest.java
Labels: code-review

#96 exception advice refactoring
  src/main/java/com/server/EZY/exception/ExceptionAdvice.java
  src/main/java/com/server/EZY/exception/ExceptionAdviceImpl.java
  src/main/java/com/server/EZY/exception/user/exception/InvalidAccessException.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
  src/test/java/com/server/EZY/exception/ExceptionAdviceTest.java
Labels: code-review

#98 Feature/users
  src/main/java/com/server/EZY/model/user/controller/CertifiedUserController.java
  src/main/java/com/server/EZY/model/user/controller/UserController.java
  src/main/java/com/server/EZY/model/user/controller/jwt/RefreshTokenController.java
  src/main/java/com/server/EZY/model/user/dto/AuthDto.java
  src/main/java/com/server/EZY/model/user/dto/NicknameDto.java
  src/main/java/com/server/EZY/model/user/dto/PasswordChangeDto.java
  src/main/java/com/server/EZY/model/user/dto/PhoneNumberDto.java
  src/main/java/com/server/EZY/model/user/dto/UserDto.java
  src/main/java/com/server/EZY/model/user/service/UserService.java
  src/main/java/com/server/EZY/model/user/service/UserServiceImpl.java
  src/main/java/com/server/EZY/model/user/service/jwt/RefreshTokenServiceImpl.java
  src/main/java/com/server/EZY/security/SecurityConfig.java
  src/main/java/com/server/EZY/security/jwt/JwtTokenProvider.java
  src/test/java/com/server/EZY/model/user/controller/CertifiedUserControllerTest.java
  src/test/java/com/server/EZY/model/user/controller/UserControllerTest.java
  src/test/java/com/server/EZY/model/user/service/UserServiceTest.java
Labels: code-review

#101 [FIX] dto 이름 변경 뒤 테스트코드에 변경사항 반영 안된 곳 반영
  src/test/java/com/server/EZY/model/user/controller/CertifiedUserControllerTest.java
  src/test/java/com/server/EZY/model/user/controller/UserControllerTest.java
Labels: bug, hotfix

#102 Develop
  .gitignore
  build.gradle
  src/main/java/com/server/EZY/EzyApplication.java
  src/main/java/com/server/EZY/exception/ExceptionAdvice.java
  src/main/java/com/server/EZY/exception/ExceptionAdviceImpl.java
  src/main/java/com/server/EZY/exception/token/TokenExceptionController.java
  src/main/java/com/server/EZY/exception/token/exception/TokenLoggedOutException.java
  src/main/java/com/server/EZY/exception/user/UserExceptionController.java
  src/main/java/com/server/EZY/exception/user/exception/InvalidAccessException.java
  src/main/java/com/server/EZY/exception/user/exception/InvalidAuthenticationNumberException.java
  src/main/java/com/server/EZY/model/baseTime/BaseTimeEntity.java
  src/main/java/com/server/EZY/model/plan/Period.java
  src/main/java/com/server/EZY/model/plan/PlanInfo.java
  src/main/java/com/server/EZY/model/plan/errand/ErrandStatus.java
  src/main/java/com/server/EZY/model/plan/headOfPlan/enumType/PlanDType.java
  src/main/java/com/server/EZY/model/plan/headOfPlan/repository/HOPRepositoryCustom.java
  src/main/java/com/server/EZY/model/plan/headOfPlan/repository/HOPRepositoryImpl.java
  src/main/java/com/server/EZY/model/plan/headOfPlan/repository/HeadOfPlanRepository.java
  src/main/java/com/server/EZY/model/plan/headOfPlan/service/HeadOfPlanService.java
  src/main/java/com/server/EZY/model/plan/personal/NewPersonalPlanEntity.java
  src/main/java/com/server/EZY/model/plan/personal/dto/NewPersonalPlanUpdateDto.java
  src/main/java/com/server/EZY/model/plan/personal/repository/NewPersonalPlanRepository.java
  src/main/java/com/server/EZY/model/plan/tag/TagEntity.java
  src/main/java/com/server/EZY/model/user/UserEntity.java
  src/main/java/com/server/EZY/model/user/controller/CertifiedUserController.java
  src/main/java/com/server/EZY/model/user/controller/UserController.java
  src/main/java/com/server/EZY/model/user/controller/jwt/RefreshTokenController.java
  src/main/java/com/server/EZY/model/user/dto/AuthDto.java
  src/main/java/com/server/EZY/model/user/dto/NicknameDto.java
  src/main/java/com/server/EZY/model/user/dto/PasswordChangeDto.java
  src/main/java/com/server/EZY/model/user/dto/PhoneNumberDto.java
  src/main/java/com/server/EZY/model/user/dto/UserDto.java
  src/main/java/com/server/EZY/model/user/service/UserService.java
  src/main/java/com/server/EZY/model/user/service/UserServiceImpl.java
  src/main/java/com/server/EZY/model/user/service/jwt/RefreshTokenServiceImpl.java
  src/main/java/com/server/EZY/response/ResponseService.java
  src/main/java/com/server/EZY/security/SecurityConfig.java
  src/main/java/com/server/EZY/security/jwt/JwtTokenProvider.java
  src/main/java/com/server/EZY/util/KeyUtil.java
  src/main/resources/application.yml
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
  src/test/java/com/server/EZY/EzyApplicationTests.java
  src/test/java/com/server/EZY/exception/ExceptionAdviceTest.java
  src/test/java/com/server/EZY/model/plan/personal/PersonalHeadOfPlanEntityTest.java
  src/test/java/com/server/EZY/model/plan/personal/PersonalPlanEntityTest.java
  src/test/java/com/server/EZY/model/user/controller/CertifiedUserControllerTest.java
  src/test/java/com/server/EZY/model/user/controller/UserControllerTest.java
  src/test/java/com/server/EZY/model/user/service/UserServiceTest.java
  src/test/java/com/server/EZY/util/KeyUtilTest.java
Labels: enhancement

#103 Add license 1
  LICENSE
Labels: enhancement, wontfix

#105 Feature/user
  src/main/java/com/server/EZY/model/user/service/UserService.java
  src/main/java/com/server/EZY/model/user/service/UserServiceImpl.java
  src/main/java/com/server/EZY/model/user/service/jwt/RefreshTokenServiceImpl.java
  src/test/java/com/server/EZY/model/user/service/UserServiceTest.java
Labels: code-review

#108 [UPDATE] change user -> member
  src/main/java/com/server/EZY/model/user/controller/CertifiedMemberController.java
  src/main/java/com/server/EZY/model/user/controller/MemberController.java
  src/main/java/com/server/EZY/model/user/dto/MemberDto.java
  src/main/java/com/server/EZY/model/user/dto/NicknameChangeDto.java
  src/main/java/com/server/EZY/model/user/repository/MemberRepository.java
  src/main/java/com/server/EZY/model/user/service/MemberService.java
  src/main/java/com/server/EZY/model/user/service/MemberServiceImpl.java
  src/main/java/com/server/EZY/model/user/service/jwt/RefreshTokenServiceImpl.java
  src/main/java/com/server/EZY/security/Authentication/MyUserDetails.java
  src/main/java/com/server/EZY/util/CurrentUserUtil.java
  src/test/java/com/server/EZY/model/plan/personal/PersonalPlanEntityTest.java
  src/test/java/com/server/EZY/model/user/UserEntityTest.java
  src/test/java/com/server/EZY/model/user/controller/CertifiedMemberControllerTest.java
  src/test/java/com/server/EZY/model/user/controller/MemberControllerTest.java
  src/test/java/com/server/EZY/model/user/service/MemberServiceTest.java
  src/test/java/com/server/EZY/security/SecurityTest.java
  src/test/java/com/server/EZY/util/CurrentUserUtilTest.java
Labels: code-review

#110 Feature/entity redesign
  src/main/java/com/server/EZY/model/baseTime/BaseTimeEntity.java
  src/main/java/com/server/EZY/model/member/MemberEntity.java
  src/main/java/com/server/EZY/model/member/controller/MemberController.java
  src/main/java/com/server/EZY/model/member/dto/AuthDto.java
  src/main/java/com/server/EZY/model/member/dto/MemberDto.java
  src/main/java/com/server/EZY/model/member/dto/PasswordChangeDto.java
  src/main/java/com/server/EZY/model/member/dto/UsernameChangeDto.java
  src/main/java/com/server/EZY/model/member/enumType/Permission.java
  src/main/java/com/server/EZY/model/member/repository/MemberRepository.java
  src/main/java/com/server/EZY/model/member/service/MemberService.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/EZY/model/member/service/jwt/RefreshTokenService.java
  src/main/java/com/server/EZY/model/member/service/jwt/RefreshTokenServiceImpl.java
  src/main/java/com/server/EZY/model/plan/personal/NewPersonalPlanEntity.java
  src/main/java/com/server/EZY/model/plan/tag/TagEntity.java
  src/main/java/com/server/EZY/security/Authentication/MyUserDetails.java
  src/main/java/com/server/EZY/security/SecurityConfig.java
  src/main/java/com/server/EZY/util/CurrentUserUtil.java
  src/test/java/com/server/EZY/model/member/MemberEntityTest.java
  src/test/java/com/server/EZY/model/member/controller/CertifiedMemberControllerTest.java
  src/test/java/com/server/EZY/model/member/controller/MemberControllerTest.java
  src/test/java/com/server/EZY/model/member/service/MemberServiceTest.java
  src/test/java/com/server/EZY/model/plan/personal/PersonalPlanEntityTest.java
  src/test/java/com/server/EZY/security/SecurityTest.java
  src/test/java/com/server/EZY/util/CurrentUserUtilTest.java
Labels: bug, code-review

#112 Feature/entity redesign
  src/main/java/com/server/EZY/model/member/MemberEntity.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/EZY/model/plan/PlanEntity.java
  src/main/java/com/server/EZY/model/plan/embeddedTypes/Period.java
  src/main/java/com/server/EZY/model/plan/embeddedTypes/PlanInfo.java
  src/main/java/com/server/EZY/model/plan/personal/NewPersonalPlanEntity.java
  src/main/java/com/server/EZY/model/plan/personal/PersonalPlanEntity.java
  src/main/java/com/server/EZY/model/plan/personal/dto/NewPersonalPlanUpdateDto.java
  src/main/java/com/server/EZY/model/plan/personal/enumType/PlanDType.java
  src/main/java/com/server/EZY/model/plan/personal/repository/NewPersonalPlanRepository.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepository.java
  src/main/java/com/server/EZY/model/plan/tag/TagEntity.java
  src/main/java/com/server/EZY/model/plan/tag/repository/TagRepository.java
  src/test/java/com/server/EZY/model/plan/personal/PersonalPlanEntityTest.java
Labels: code-review

#114 Supplement User
  src/main/java/com/server/EZY/model/member/controller/MemberController.java
  src/main/java/com/server/EZY/model/member/controller/jwt/RefreshTokenController.java
  src/main/java/com/server/EZY/model/member/service/MemberService.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/EZY/security/Authentication/MyUserDetails.java
  src/main/java/com/server/EZY/security/SecurityConfig.java
  src/test/java/com/server/EZY/model/member/controller/MemberControllerTest.java
  src/test/java/com/server/EZY/model/member/service/MemberServiceTest.java
  src/test/java/com/server/EZY/security/Authentication/MyUserDetailsTest.java
Labels: code-review

#116 [Incomplete] Feature/personal plan service 작성 중..
  src/main/java/com/server/EZY/model/plan/personal/dto/PersonalPlanSetDto.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImpl.java
Labels: wontfix

#120 Develop merge & PersonalPlanSave 비즈니스 로직 merge
  src/main/java/com/server/EZY/exception/ExceptionAdvice.java
  src/main/java/com/server/EZY/exception/ExceptionAdviceImpl.java
  src/main/java/com/server/EZY/exception/user/MemberExceptionController.java
  src/main/java/com/server/EZY/exception/user/UserExceptionController.java
  src/main/java/com/server/EZY/exception/user/exception/MemberNotFoundException.java
  src/main/java/com/server/EZY/exception/user/exception/UserNotFoundException.java
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/EZY/model/plan/PlanEntity.java
  src/main/java/com/server/EZY/model/plan/personal/PersonalPlanEntity.java
  src/main/java/com/server/EZY/model/plan/personal/controller/PersonalPlanController.java
  src/main/java/com/server/EZY/model/plan/personal/dto/PersonalPlanSetDto.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImpl.java
  src/main/java/com/server/EZY/model/plan/tag/repository/TagRepository.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
  src/test/java/com/server/EZY/exception/ExceptionAdviceTest.java
  src/test/java/com/server/EZY/model/plan/personal/PersonalPlanEntityTest.java
  src/test/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImplTest.java
Labels: code-review

#121 about user
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/EZY/model/member/service/jwt/RefreshTokenServiceImpl.java
  src/main/java/com/server/EZY/security/SecurityConfig.java
  src/main/java/com/server/EZY/security/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: code-review

#122 Feature/personal plan read
  src/main/java/com/server/EZY/model/plan/personal/controller/PersonalPlanController.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepoCustom.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepoImpl.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepository.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImpl.java
  src/test/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImplTest.java
Labels: code-review

#124 #121 에서 요구해주신 exception 추가
  src/main/java/com/server/EZY/exception/ExceptionAdvice.java
  src/main/java/com/server/EZY/exception/ExceptionAdviceImpl.java
  src/main/java/com/server/EZY/exception/token/TokenExceptionController.java
  src/main/java/com/server/EZY/exception/token/exception/AuthorizationHeaderIsEmpty.java
  src/main/java/com/server/EZY/exception/token/exception/RefreshTokenHeaderIsEmpty.java
  src/main/java/com/server/EZY/exception/user/MemberExceptionController.java
  src/main/java/com/server/EZY/exception/user/exception/MemberAlreadyExistException.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
  src/test/java/com/server/EZY/exception/ExceptionAdviceTest.java
Labels: code-review

#127 Feature/personal plan read
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepoCustom.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepoImpl.java
  src/main/java/com/server/EZY/model/plan/personal/repository/PersonalPlanRepository.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImpl.java
  src/test/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImplTest.java
Labels: code-review

#130 [ADD] about errands controller
  src/main/java/com/server/EZY/model/plan/errand/controller/ErrandController.java
  src/main/java/com/server/EZY/model/plan/errand/controller/ErrandStatusCycleController.java
  src/main/java/com/server/EZY/security/SecurityConfig.java
Labels: code-review

#129 Feature/personal plan delete
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImpl.java
  src/main/java/com/server/EZY/model/plan/personal/service/strategy/PersonalPlanStrategy.java
  src/main/java/com/server/EZY/model/plan/personal/service/strategy/PersonalPlanStrategyImpl.java
  src/test/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImplTest.java
Labels: code-review, enhancement

#131 [ADD] Tag controller
  src/main/java/com/server/EZY/model/plan/tag/controller/TagController.java
  src/main/java/com/server/EZY/security/SecurityConfig.java
Labels: code-review

#126 [UPDATE] about Member Exception
  src/main/java/com/server/EZY/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/EZY/security/jwt/JwtTokenProvider.java
Labels: code-review

#135 Feature/personal plan
  src/main/java/com/server/EZY/model/plan/personal/PersonalPlanEntity.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanService.java
  src/main/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImpl.java
  src/test/java/com/server/EZY/model/plan/personal/PersonalPlanEntityTest.java
  src/test/java/com/server/EZY/model/plan/personal/service/PersonalPlanServiceImplTest.java
Labels: code-review, enhancement
